#!/bin/sh -e
#############################################################################
# Copyright 2021 Ramon Fischer                                              #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#     http://www.apache.org/licenses/LICENSE-2.0                            #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################

version="$1"
bootopt=""

command -v update-initramfs >/dev/null 2>&1 || exit 0

# passing the kernel version is required
if [ -z "${version}" ]; then
    echo >&2 "W: initramfs-tools: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
    exit 2
fi

# exit if kernel does not need an initramfs
if [ "$RPI_INITRD" = 'No' ]; then
    # comment initramfs entries in /boot/config.txt
    if [ -f "/boot/config.txt" ]
    then
        if /bin/grep --quiet "^initramfs " "/boot/config.txt"
        then
            /bin/sed --in-place "s/^initramfs /#initramfs /" "/boot/config.txt"
        else
            exit 0
        fi
    else
        echo "\e[01;31mCould not find file '/boot/config.txt'.\e[0m" >&2
        exit 1
    fi

    exit 0
fi

# absolute file name of kernel image may be passed as a second argument;
# create the initrd in the same directory
if [ -n "$2" ]; then
    bootdir=$(dirname "$2")
    bootopt="-b ${bootdir}"
fi

# avoid running multiple times
if [ -n "$DEB_MAINT_PARAMS" ]; then
    eval set -- "$DEB_MAINT_PARAMS"
    if [ -z "$1" ] || [ "$1" != "configure" ]; then
        exit 0
    fi
fi

# we're good - create initramfs.  update runs do_bootloader
# shellcheck disable=SC2086
INITRAMFS_TOOLS_KERNEL_HOOK=1 update-initramfs -c -k "${version}" ${bootopt} >&2

# add "initramfs" entry in "/boot/config.txt"
if [ -f "/boot/config.txt" ]
then
    if /bin/grep --quiet "^#initramfs " "/boot/config.txt"
    then
        /bin/sed --in-place "s/^#initramfs /initramfs /" "/boot/config.txt"
    elif ! /bin/grep --quiet "^initramfs " "/boot/config.txt"
    then
        echo "initramfs initramfs.cpio.gz followkernel" >> "/boot/config.txt"
    fi
else
    echo "\e[01;31mCould not find file '/boot/config.txt'.\e[0m" >&2
    exit 1
fi

# be conform with the entry in "/boot/config.txt"
if [ -f "/boot/initrd.img-${version}" ]
then
    /bin/mv --force --verbose "/boot/initrd.img-${version}" "/boot/initramfs.cpio.gz"
else
    echo "\e[01;31mCould not find file '/boot/initrd.img-${version}'.\e[0m" >&2
    exit 1
fi
